# MegaLinter configuration file
# More info at https://megalinter.io
---
# Configuration documentation: https://megalinter.io/latest/configuration/
# Linters documentation: https://megalinter.io/latest/descriptors/

# All available variables are described in documentation
# https://megalinter.io/latest/configuration/#all-available-variables
APPLY_FIXES: none
PRINT_ALL_FILES: true

LOG_LEVEL: DEBUG

FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
ENABLE_LINTERS:
  # https://megalinter.io/latest/descriptors/java_checkstyle/
  - JAVA_CHECKSTYLE
  # https://megalinter.io/latest/descriptors/java_pmd/
  - JAVA_PMD

JAVA_CHECKSTYLE_CONFIG_FILE: megalinter-config/google-checks.xml
JAVA_PMD_CONFIG_FILE: megalinter-config/pmd-ruleset.xml

FILTER_REGEX_INCLUDE: (lib/src)

# Exclude unessential directories
FILTER_REGEX_EXCLUDE: (target/|.venv/|.idea/|.git/)
