fail_fast: false
repos:
  - repo: local
    hooks:
      - id: mvn-test-ensure4j
        name: Maven Test ensure4j
        entry: mise mvn:test
        language: system
        files: ^lib/src
        require_serial: true
        pass_filenames: false