[tools]
java = "graalvm-community-25.0.2"
maven = "3.9.12"
python = "3.14.4"

[env]
_.python.venv = ".venv"

[tasks."mvn:validate"]
dir = "./lib"
run = "mvn clean validate"

[tasks.mvn-format]
description = "Sort pom.xml and format java code"
dir = "./lib"
run = [
    "mvn sortpom:sort",
    "mvn fmt:format",
]

[tasks.megalint]
description = "Megalint with Java flavor"
run = "docker run --rm -v $(pwd):/tmp/lint:rw oxsecurity/megalinter-java"