name: Add Release Label to PR

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - main

permissions:
  pull-requests: write
  id-token: write

jobs:
  add-release-label:
    runs-on: ubuntu-latest
    env:
      LABEL: "3.0.4"
    steps:
      - name: Add hardcoded release label
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ env.LABEL }}"