---
name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Push new changes to CHANGELOG.md
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git User
        # language=bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate changelog
        # https://github.com/orhun/git-cliff-action
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push origin main
