---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter

on:
  pull_request:
    branches:
      - main

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: write
      issues: write
      statuses: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: MegaLinter
        continue-on-error: true
        # https://github.com/oxsecurity/megalinter
        uses: oxsecurity/megalinter/flavors/java@15e5b45552097e318c93de385779ce3b1084052c # v10.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive MegaLinter report
        if: success() || failure()
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
          if-no-files-found: warn
          retention-days: 3

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        # https://github.com/github/codeql-action
        uses: github/codeql-action/upload-sarif@v4.37.9 # zizmor: ignore[unpinned-uses]
        with:
          sarif_file: "megalinter-reports/megalinter-report.sarif"
