---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: MegaLinter

on:
  pull_request:
    paths:
      - "lib/src/**"
    branches:
      - main

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: write
      issues: write
      statuses: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: MegaLinter
        continue-on-error: false
        # https://github.com/oxsecurity/megalinter
        uses: oxsecurity/megalinter/flavors/java@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive MegaLinter report
        if: success() || failure()
        # https://github.com/actions/upload-artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
          if-no-files-found: warn
          retention-days: 3

      - name: Upload MegaLinter scan results to GitHub Security tab
        if: success() || failure()
        # https://github.com/github/codeql-action
        uses: github/codeql-action/upload-sarif@v4 # zizmor: ignore[unpinned-uses]
        with:
          sarif_file: 'megalinter-reports/megalinter-report.sarif'
