---
name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "SemVer Release Type"
        required: true
        default: "Patch"
        type: choice
        options:
          - Major
          - Minor
          - Patch

jobs:
  release:
    name: Maven Release & Upload Artifact to Maven Central
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      previous_tag: ${{ steps.set_previous_tag.outputs.tag }}
      current_tag: ${{ steps.set_current_tag.outputs.tag }}
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Configure Git User
        # language=bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Java
        # https://github.com/actions/setup-java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 25
          distribution: "zulu"
          server-id: central
          server-username: SONAR_USERNAME
          server-password: SONAR_PASSWORD
          cache: maven

      - name: Set previous Git tag for GitHub Release
        id: set_previous_tag
        # language=bash
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "PREVIOUS_TAG: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Determine Maven Version Type (projectVersionPolicyId)
        id: determine_version_type
        env:
          VERSION_TYPE: ${{ github.event.inputs.version_type }}
        # language=bash
        run: |
          case "$VERSION_TYPE" in
            Major)
              RELEASE_TYPE="SemVerMajorRelease"
              ;;
            Minor)
              RELEASE_TYPE="SemVerMinorRelease"
              ;;
            Patch)
              RELEASE_TYPE="SemVerPatchDevelopment"
              ;;
            *)
              echo "Unknown version type: $VERSION_TYPE"
              exit 1
              ;;
          esac
          echo "VERSION_POLICY=$RELEASE_TYPE" >> $GITHUB_ENV
          echo "projectVersionPolicyId: $RELEASE_TYPE"

      - name: Release to Maven Central
        env:
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          VERSION_POLICY: ${{ env.VERSION_POLICY }}
        # language=bash
        run: |
          MAVEN_ARGS="-B -V -e -ntp -Dstyle.color=always -DskipTests=true -f lib/pom.xml"
          RELEASE_ARGS="-Darguments=-B -V -e -ntp -Dstyle.color=always -DskipTests=true"
          mvn ${MAVEN_ARGS} \
          -DprojectVersionPolicyId=$VERSION_POLICY \
          "${RELEASE_ARGS}" \
          release:prepare release:perform
          git push origin main --tags

      - name: Set the Current Git tag for GitHub Release
        id: set_current_tag
        # language=bash
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "CURRENT_TAG: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  deploy_pages:
    name: Deploy Maven Site to GitHub Pages
    needs: release
    permissions:
      pages: write
      id-token: write
    env:
      CURRENT_TAG: ${{ needs.release.outputs.current_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ env.CURRENT_TAG }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Java
        # https://github.com/actions/setup-java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 25
          distribution: "zulu"
          cache: maven

      - name: Build site
        # language=bash
        run: |
          MAVEN_ARGS="-B -V -e -ntp -Dstyle.color=always -f lib/pom.xml"
          mvn ${MAVEN_ARGS} clean test site

      - name: Upload Pages Artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./lib/target/site

      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0

  create_github_release:
    name: Create GitHub Release
    needs: release
    permissions:
      contents: write
      pull-requests: read
    env:
      FROM_TAG: ${{ needs.release.outputs.previous_tag }}
      TO_TAG: ${{ needs.release.outputs.current_tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build Github Changelog
        id: github_release
        # https://github.com/mikepenz/release-changelog-builder-action
        uses: mikepenz/release-changelog-builder-action@c9bcd8238b6f41e05561348339429d360b1c0247 # v.6.2.3
        with:
          fromTag: "${{ env.FROM_TAG }}"
          toTag: "${{ env.TO_TAG }}"
          mode: "PR"
          # language=JSON
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                  "title": "## New Features ",
                  "labels": [
                    "feat"]
                },
                {
                  "title": "## Docs 📝",
                  "labels": [
                    "docs"]
                },
                {
                  "title": "## Test 🧪",
                  "labels": [
                    "test"
                  ]
                },
                {
                  "title": "## Dependency 📦",
                  "labels": [
                    "dependencies"
                  ]
                },
                {
                  "title": "## Other 🔧 🧹 ⚙️",
                  "labels": [
                    "chore",
                    "github-actions"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v.3.0.2
        with:
          tag_name: "${{ env.TO_TAG }}"
          body: ${{steps.github_release.outputs.changelog}}
