---

name: Release and Upload Pages

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git User
        # language=bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Java
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu'
          server-id: central
          server-username: SONAR_USERNAME
          server-password: SONAR_PASSWORD
          cache: maven

      - name: Set previous Git tag for GitHub Release
        # language=bash
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "PREVIOUS_TAG: $TAG"
          echo "PREVIOUS_TAG=$TAG" >> $GITHUB_ENV

      - name: Release to Maven Central
        env:
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        with: 
          token: ${{ secrets.PAT_TOKEN }}
        # language=bash
        run: |
          export GPG_TTY=$(tty)
          mvn -B --no-transfer-progress --file lib/pom.xml release:prepare
          mvn -B --no-transfer-progress --file lib/pom.xml release:perform
          git push origin main --tags

      - name: Upload Pages Artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./lib/target/site

      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v5

      - name: Set the Current Git tag for GitHub Release
        # language=bash
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "CURRENT_TAG: $TAG"
          echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV

      - name: Build Github Changelog
        id: github_release
        # https://github.com/mikepenz/release-changelog-builder-action
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          fromTag: "${{ env.PREVIOUS_TAG }}"
          toTag: "${{ env.CURRENT_TAG }}"
          mode: "PR"
          owner: "mangila"
          repository: "ensure4j"
          # language=JSON
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                  "title": "## New Features ",
                  "labels": ["feat"]
                },
                {
                  "title": "## Docs 📝",
                  "labels": ["docs"]
                },
                {
                  "title": "## Test 🧪",
                  "labels": ["test"]
                },
                {
                  "title": "## Dependency 📦",
                  "labels": ["dependencies"]
                },
                {
                  "title": "## Other 🔧 🧹 ⚙️",
                  "labels": ["chore"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.CURRENT_TAG }}
          body: ${{steps.github_release.outputs.changelog}}