name: Release and Upload Pages

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup Java
      - name: Setup Java
        # https://github.com/actions/setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'zulu'
          server-id: central
          server-username: SONAR_USERNAME
          server-password: SONAR_PASSWORD
          cache: maven
      # Set previous Git tag
      - name: Set previous Git tag for GitHub Release
        id: previous_tag
        # language=bash
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          echo "tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
      # Post JARs to Maven Central
      - name: Release to Maven Central
        env:
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        # language=bash
        run: |
          export GPG_TTY=$(tty)
          git config --global user.name "GitHub Actions"
          git config --global user.email "olsson.erik1993@gmail.com"
          mvn -B --file pom.xml release:prepare
          mvn -B --file pom.xml release:perform
          git push origin main --tags
      # Upload GitHub pages
      - name: Upload Pages Artifact
        # https://github.com/actions/upload-pages-artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./lib/target/site
      # Deploy GitHub pages
      - name: Deploy to GitHub Pages
        id: deployment
        # https://github.com/actions/deploy-pages
        uses: actions/deploy-pages@v4
        # Set the new tag
      - name: Set the Current Git tag for GitHub Release
        id: current_tag
        # language=bash
        run: |
          CURRENT_TAG=$(git describe --tags --abbrev=0)
          echo "CURRENT_TAG: $CURRENT_TAG"
          echo "tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
      # Build Github Changelog
      - name: Build Github Changelog
        id: github_release
        # https://github.com/mikepenz/release-changelog-builder-action
        uses: mikepenz/release-changelog-builder-action@v6
        with:
          fromTag: "${{ steps.previous_tag.outputs.tag }}"
          toTag: "${{ steps.current_tag.outputs.tag }}"
          mode: "PR"
          # language=JSON
          configurationJson: |
            {
              "template": "## 📝 Release Notes\n\n#{{CHANGELOG}}",
              "categories": [
                {
                  "title": "## 🚀 New Features",
                  "labels": [
                    "feat"]
                },        
                {
                  "title": "## 💬 Other",
                  "labels": [
                    "chore",
                    "dependencies",
                    "docs",
                    "fix",
                    "refactor",
                    "test"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Create GitHub Release
      - name: Create GitHub Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.current_tag.outputs.tag }}
          body: ${{steps.github_release.outputs.changelog}}