---
name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Java
        # https://github.com/actions/setup-java
        uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          java-version: 25
          distribution: "zulu"
          cache: maven

      - name: Run tests (lib)
        run: |
          MAVEN_ARGS="-B -V -e -ntp -Dstyle.color=always -f lib/pom.xml"
          mvn $MAVEN_ARGS package

      - name: JaCoCo Report to PR
        # https://github.com/Madrapps/jacoco-report
        uses: madrapps/jacoco-report@e51ce1f46f7f8b5331593f935e59cbaf44b84920 # v1.8.0
        with:
          paths: lib/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 90
          title: "# :bar_chart: Coverage Report"
          pass-emoji: ":green_circle:"
          fail-emoji: ":red_circle:"
          update-comment: true
